name: Deploy to Server via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 109.196.101.77 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh root@109.196.101.77 << 'EOF'
            # Переход в директорию проекта
            cd ~/tg_bots/evening_tg_bot/

            # Меняем origin на HTTPS (один раз)
            git remote set-url origin https://github.com/socolov99/evening_tg_bot.git

            # Обновляем код
            git pull origin master

            # Устанавливаем pip, если нужно
            apt update
            apt install -y python3-pip python3-venv

            # Создаём виртуальное окружение, если его нет
            [ -d .venv ] || python3 -m venv .venv

            # Активируем виртуальное окружение
            source .venv/bin/activate

            # Обновляем pip внутри venv и ставим зависимости
            pip install --upgrade pip
            pip install -r requirements.txt

            # Завершаем старую screen-сессию
            screen -S bot -X quit || true

            # Запускаем main.py в новой screen-сессии с активированным venv
            screen -dmS bot bash -c 'source .venv/bin/activate && python main.py'
          EOF
